# **Creating, Reading and Writing**

Pandas is a python library for data analysis.

In [1]:
import pandas as pd

**Creating data**

Objects of pandas:
1. **DataFrame**- Is a table. Contains an array of individual entries, each having a certain value. (Made up series)

We use the pd.DataFrame() method to create a dataframe object

In [2]:
#create an example data frame
pd.DataFrame({
    "Cars":['Ferari', 'Bugatti', 'Ford'],
    "Price":[100000,223000,89999],
    "Reviews":['Fancy','Expensive','Quick']
})

      Cars   Price    Reviews
0   Ferari  100000      Fancy
1  Bugatti  223000  Expensive
2     Ford   89999      Quick

2. **Series** -is a sequence of data values. If a dataframe is a table then a series is a list.

*Note*: A series is a single column of a DataFrame.

In [3]:
#create series
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
#we can assign index name to a series but it does not have a column name
pd.Series([23,24,25], index=['Mark','Jaba','Allan'])

Mark     23
Jaba     24
Allan    25
dtype: int64

# **Reading data Files**

Most of the time we work with data that already exists. Data can be stored in a number of formats, the most basic being CSV(Comma Separated Value) file.

*Note*: Use **pd.read_csv()**  function to read a csv file to a DataFrame.

Download the dataset:https://www.kaggle.com/datasets/christopheiv/winemagdata130k

In [6]:
#load csv file
wine_reviews=pd.read_csv('sample_data/winemag-data.csv')

In [7]:
#use head method to view the first rows of the df
wine_reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [8]:
#Shape attribut displays how large the resulting dataframe is
wine_reviews.shape  #(rows, columns)

(43904, 14)

In [9]:
#Lets see the column names
list(wine_reviews.columns)

['Unnamed: 0',
 'country',
 'description',
 'designation',
 'points',
 'price',
 'province',
 'region_1',
 'region_2',
 'taster_name',
 'taster_twitter_handle',
 'title',
 'variety',
 'winery']

In [10]:
#get info- column data types, misssing values can be seen from this
wine_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43904 entries, 0 to 43903
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             43904 non-null  int64
 1   country                43886 non-null  object
 2   description            43904 non-null  object
 3   designation            31330 non-null  object
 4   points                 43904 non-null  int64
 5   price                  40778 non-null  float64
 6   province               43885 non-null  object
 7   region_1               36681 non-null  object
 8   region_2               16864 non-null  object
 9   taster_name            34901 non-null  object
 10  taster_twitter_handle  33242 non-null  object
 11  title                  43903 non-null  object
 12  variety                43903 non-null  object
 13  winery                 43903 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 4.7+ MB

In [11]:
#Find columns with missing values and number missing in the columns
wine_reviews.isnull().sum()

Unnamed: 0                   0
country                     18
description                  0
designation              12574
points                       0
price                     3126
province                    19
region_1                  7223
region_2                 27040
taster_name               9003
taster_twitter_handle    10662
title                        1
variety                      1
winery                       1
dtype: int64

In [13]:
#lets see countries we got reviews from
wine_reviews['country'].value_counts()

np.int64(43886)

# **Saving Dataframe to File**

We are also able to save a dataframe to different file formats for this example lets go with csv file

In [14]:
#create a dataframe
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [15]:
#save it to csv
animals.to_csv('animals.csv')

In [17]:
#lets clean our data we loaded previously
#--Drop null values
wine_reviews_new=wine_reviews.dropna()

In [20]:
#now lets select relevant columns
wine_reviews_new=wine_reviews_new[['country','description','taster_twitter_handle','winery']]

In [21]:
#Save it now
wine_reviews_new.to_csv('wine_reviews_cleaned.csv')